/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useScroll } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_73: THREE.SkinnedMesh
    Object_74: THREE.SkinnedMesh
    Object_75: THREE.SkinnedMesh
    Object_76: THREE.SkinnedMesh
    Object_77: THREE.SkinnedMesh
    Object_78: THREE.SkinnedMesh
    Object_79: THREE.SkinnedMesh
    Object_80: THREE.SkinnedMesh
    Object_81: THREE.SkinnedMesh
    Object_82: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    frames: THREE.MeshStandardMaterial
    ['red.001']: THREE.MeshStandardMaterial
    ['blue.001']: THREE.MeshStandardMaterial
    ['FrontLogo.001']: THREE.MeshStandardMaterial
    ['webshooters.001']: THREE.MeshStandardMaterial
    ['Rubber.001']: THREE.MeshStandardMaterial
    ['BackLogo.001']: THREE.MeshStandardMaterial
    eyes: THREE.MeshStandardMaterial
    ['Cartridges.001']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

const KEYFRAMES = [
  // 0. Home - Head Focus
  {
    position: [0, -14.5, 0] as [number, number, number],
    rotation: [0, 0, 0] as [number, number, number],
    scale: 7.8,
  },
  // 1. About - Chest Focus
  {
    position: [0, -10.5, 0.2] as [number, number, number],
    rotation: [0, 0, 0] as [number, number, number],
    scale: 7.2,
  },
  // 2. Skills - Right Web Shooter Focus
  {
    position: [2.8, -9.0, 1.8] as [number, number, number],
    rotation: [0.1, 0.9, 0.2] as [number, number, number],
    scale: 9.0,
  },
  // 3. Projects - Back Focus
  {
    position: [0, -10.5, 0.8] as [number, number, number],
    rotation: [0, Math.PI, 0] as [number, number, number],
    scale: 7.0,
  },
  // 4. Articles - Left Web Shooter Focus
  {
    position: [-2.8, -9.0, 1.8] as [number, number, number],
    rotation: [0.1, -0.9, -0.2] as [number, number, number],
    scale: 9.0,
  },
  // 5. Volunteering - Left Thigh Focus (Facing slightly forward)
  {
    position: [-1.2, -6.8, 1.0] as [number, number, number],
    rotation: [0, 0.3, 0] as [number, number, number],
    scale: 8.5,
  },
  // 6. Contact - Between legs / Right Thigh Focus
  {
    position: [1.0, -5.5, 1.0] as [number, number, number],
    rotation: [0, -0.3, 0] as [number, number, number],
    scale: 8.5,
  }
];

export default function SpiderManModel(props: any) {
  const group = useRef<THREE.Group>(null)
  const { scene } = useGLTF('/spiderman.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  
  const scroll = useScroll()

  // Pre-calculate keyframe quaternions for slerp
  const quaternions = React.useMemo(() => {
    return KEYFRAMES.map((key) => {
      return new THREE.Quaternion().setFromEuler(
        new THREE.Euler(key.rotation[0], key.rotation[1], key.rotation[2])
      );
    });
  }, []);

  // Expose the scroll container globally so Navbar can access it
  React.useEffect(() => {
    if (scroll?.el) {
      (window as any).scrollContainer = scroll.el;
    }
  }, [scroll]);

  useFrame((state) => {
    if (!group.current || !scroll) return
    
    // offset goes from 0 to 1 based on scroll position
    const offset = scroll.offset;
    
    // Convert scroll offset to keyframe scale (6 intervals between 7 keyframes)
    const progress = offset * 6;
    const index = Math.min(Math.floor(progress), 5);
    const fraction = progress - index;
    
    // Smooth transition curve (smoothstep)
    const t = fraction * fraction * (3 - 2 * fraction);
    
    const startKey = KEYFRAMES[index];
    const endKey = KEYFRAMES[index + 1];
    
    // Interpolate target position
    const targetPos = new THREE.Vector3(
      THREE.MathUtils.lerp(startKey.position[0], endKey.position[0], t),
      THREE.MathUtils.lerp(startKey.position[1], endKey.position[1], t),
      THREE.MathUtils.lerp(startKey.position[2], endKey.position[2], t)
    );
    
    // Interpolate target scale
    const targetScale = THREE.MathUtils.lerp(startKey.scale, endKey.scale, t);
    
    // Interpolate target rotation using Quaternion slerp
    const targetQuat = new THREE.Quaternion().slerpQuaternions(
      quaternions[index],
      quaternions[index + 1],
      t
    );
    
    // Add subtle idle floating animation (only apply when not scrolling heavily)
    const time = state.clock.getElapsedTime();
    const floatY = Math.sin(time * 1.5) * 0.12;
    const floatX = Math.cos(time * 1.0) * 0.04;
    
    targetPos.y += floatY;
    targetPos.x += floatX;
    
    // Lerp actual model group position, scale, and rotation
    group.current.position.lerp(targetPos, 0.08);
    group.current.quaternion.slerp(targetQuat, 0.08);
    
    const currentScale = group.current.scale.x;
    const nextScale = THREE.MathUtils.lerp(currentScale, targetScale, 0.08);
    group.current.scale.set(nextScale, nextScale, nextScale);
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_73.geometry} material={materials.frames} skeleton={nodes.Object_73.skeleton} />
          <skinnedMesh geometry={nodes.Object_74.geometry} material={materials['red.001']} skeleton={nodes.Object_74.skeleton} />
          <skinnedMesh geometry={nodes.Object_75.geometry} material={materials['blue.001']} skeleton={nodes.Object_75.skeleton} />
          <skinnedMesh geometry={nodes.Object_76.geometry} material={materials['FrontLogo.001']} skeleton={nodes.Object_76.skeleton} />
          <skinnedMesh geometry={nodes.Object_77.geometry} material={materials['webshooters.001']} skeleton={nodes.Object_77.skeleton} />
          <skinnedMesh geometry={nodes.Object_78.geometry} material={materials['Rubber.001']} skeleton={nodes.Object_78.skeleton} />
          <skinnedMesh geometry={nodes.Object_79.geometry} material={materials['BackLogo.001']} skeleton={nodes.Object_79.skeleton} />
          <skinnedMesh geometry={nodes.Object_80.geometry} material={materials.eyes} skeleton={nodes.Object_80.skeleton} />
          <skinnedMesh geometry={nodes.Object_81.geometry} material={materials['Cartridges.001']} skeleton={nodes.Object_81.skeleton} />
          <skinnedMesh geometry={nodes.Object_82.geometry} material={materials['Glass.001']} skeleton={nodes.Object_82.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spiderman.gltf')
